name: Herring Cove
author: Herring Cove
baseurl: /
description: theme for jekyll
github: http://www.github.com/begonia1005
twitter: http://www.twitter.com/
facebook: https://www.facebook.com/kevin.he.980315
linkedin: https://www.linkedin.com/in/tianyi-he-b195021b4/
email: 1507533037[at]qq.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
